### ISSUE TITLE
readme clarifications

### ISSUE THREAD

**Issue by cropredyHelix** [bobalicious/amoss#112]
Well, this repo is impressive. As an ApexMocks user, I have a lot to think about to see where this library would make my life easier. Thorough documentation.

That said, this example threw me for a loop:

```
Test.startTest();
    Order order = new Order().setDeliveryDate( deliveryDate ).setDeliveryPostcode( deliveryPostcode );
    Boolean scheduled = order.scheduleDelivery( deliveryProviderDouble );
Test.stopTest();
```

`Order` here is a customType?  And not the OOTB `Order` object?  Confusing to say the least, especially if the org has enabled Orders in config.

**Comment by bobalicious** [comment]
That's a very fair point.  Originally the examples were all prefixed with `AmossExample_`, and I had forgotten why - this is why!

Will update to a less misleading example

**Comment by bobalicious** [comment]
README updated, now references 'DeliveryOrder'.

(thanks for reporting, and for the compliment on the repo!)
